In [28]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

In [2]:
datasets = sns.get_dataset_names()
datasets

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
miles_per_gallon = sns.load_dataset('mpg')
miles_per_gallon

      mpg  cylinders  ...  origin                       name
0    18.0          8  ...     usa  chevrolet chevelle malibu
1    15.0          8  ...     usa          buick skylark 320
2    18.0          8  ...     usa         plymouth satellite
3    16.0          8  ...     usa              amc rebel sst
4    17.0          8  ...     usa                ford torino
..    ...        ...  ...     ...                        ...
393  27.0          4  ...     usa            ford mustang gl
394  44.0          4  ...  europe                  vw pickup
395  32.0          4  ...     usa              dodge rampage
396  28.0          4  ...     usa                ford ranger
397  31.0          4  ...     usa                 chevy s-10

[398 rows x 9 columns]

In [27]:
miles_per_gallon.tail()

      mpg  cylinders  displacement  ...  model_year  origin             name
393  27.0          4         140.0  ...          82     usa  ford mustang gl
394  44.0          4          97.0  ...          82  europe        vw pickup
395  32.0          4         135.0  ...          82     usa    dodge rampage
396  28.0          4         120.0  ...          82     usa      ford ranger
397  31.0          4         119.0  ...          82     usa       chevy s-10

[5 rows x 9 columns]

In [4]:
miles_per_gallon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [5]:
miles_per_gallon.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [6]:
miles_per_gallon.describe()

              mpg   cylinders  ...  acceleration  model_year
count  398.000000  398.000000  ...    398.000000  398.000000
mean    23.514573    5.454774  ...     15.568090   76.010050
std      7.815984    1.701004  ...      2.757689    3.697627
min      9.000000    3.000000  ...      8.000000   70.000000
25%     17.500000    4.000000  ...     13.825000   73.000000
50%     23.000000    4.000000  ...     15.500000   76.000000
75%     29.000000    8.000000  ...     17.175000   79.000000
max     46.600000    8.000000  ...     24.800000   82.000000

[8 rows x 7 columns]

In [7]:
miles_per_gallon['horsepower'] = miles_per_gallon['horsepower'].fillna(miles_per_gallon['horsepower'].mean())

In [8]:
miles_per_gallon.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [9]:
miles_per_gallon.tail()

      mpg  cylinders  displacement  ...  model_year  origin             name
393  27.0          4         140.0  ...          82     usa  ford mustang gl
394  44.0          4          97.0  ...          82  europe        vw pickup
395  32.0          4         135.0  ...          82     usa    dodge rampage
396  28.0          4         120.0  ...          82     usa      ford ranger
397  31.0          4         119.0  ...          82     usa       chevy s-10

[5 rows x 9 columns]

In [10]:
copy_miles_per_gallon = miles_per_gallon.drop(['name','origin'],axis=1).copy()
copy_miles_per_gallon

      mpg  cylinders  displacement  ...  weight  acceleration  model_year
0    18.0          8         307.0  ...    3504          12.0          70
1    15.0          8         350.0  ...    3693          11.5          70
2    18.0          8         318.0  ...    3436          11.0          70
3    16.0          8         304.0  ...    3433          12.0          70
4    17.0          8         302.0  ...    3449          10.5          70
..    ...        ...           ...  ...     ...           ...         ...
393  27.0          4         140.0  ...    2790          15.6          82
394  44.0          4          97.0  ...    2130          24.6          82
395  32.0          4         135.0  ...    2295          11.6          82
396  28.0          4         120.0  ...    2625          18.6          82
397  31.0          4         119.0  ...    2720          19.4          82

[398 rows x 7 columns]

In [11]:
#using the StratifiedShuffleSplit to split the dataset properly
split = StratifiedShuffleSplit(n_splits=1,test_size=0.1,random_state=78)
for train_index,test_index in split.split(copy_miles_per_gallon,copy_miles_per_gallon['cylinders']):
  strat_train_set = copy_miles_per_gallon.loc[train_index]
  strat_test_set = copy_miles_per_gallon.loc[test_index]

In [12]:
strat_train_set.shape

(358, 7)

In [13]:
labels = strat_train_set['mpg']
features = strat_train_set.drop(['mpg'],axis=1)

In [14]:
labels

379    36.0
88     14.0
240    30.5
75     14.0
59     23.0
       ...
45     18.0
341    23.5
164    21.0
73     13.0
353    33.0
Name: mpg, Length: 358, dtype: float64

In [15]:
#forming an pipeline so that the numerical value can be scale down to lower value for better processing
num_pipeline = Pipeline([
    ('scaler', StandardScaler())
])
prepared_data = num_pipeline.fit_transform(features)

In [16]:
#Loading different models

#linear Model
linearmodel = LinearRegression()
linearmodel.fit(prepared_data,labels)

#Decision Tree Model
decisiontree= DecisionTreeRegressor()
decisiontree.fit(prepared_data,labels)

#random forest model
randomforest = RandomForestRegressor()
randomforest.fit(prepared_data,labels)

RandomForestRegressor()

In [17]:
#lets run the model on the test data

#linear Model
strat_test_set_features = strat_test_set.drop(['mpg'],axis=1)
prepared_test_data = num_pipeline.transform(strat_test_set_features)
predictions = linearmodel.predict(prepared_test_data)
print(predictions)

[21.41733351 24.18735826 12.51798961 26.03853088 25.64939932 32.39333759
 24.44905195 33.37239526 13.9336442  23.97943573 33.62342799 22.92599608
 22.38845089 26.31620029 31.54525807 22.0336546  28.78825735 26.24213147
 29.73916477 34.39294177  9.93326892 21.23070977 34.28604126 16.61940246
 20.05872526 16.06363209 31.96146533 24.56105441 11.95712059 14.63481509
 20.84411796 31.14068783 14.37483588 24.75503263 23.25078636 27.2039147
 26.91438713 10.46371486 32.6569346  21.17518384]

In [20]:
#checking the accuracy of the linear model
accuracy = r2_score(strat_test_set['mpg'],predictions)
print(f"Accuracy (R2 Score) is: {accuracy:.2%}")

Accuracy (R2 Score) is: 79.02%

In [23]:
#Decisiontree Model
strat_test_set_features = strat_test_set.drop(['mpg'],axis=1)
prepared_test_data = num_pipeline.transform(strat_test_set_features)
predictions_decisiontree = decisiontree.predict(prepared_test_data)
print(predictions_decisiontree)

[20.5 20.  14.  16.2 25.  38.  22.  38.  15.  20.2 35.1 23.8 23.8 25.
 30.  18.  30.  20.  29.  33.  13.  25.  36.  14.  19.2 15.5 35.1 28.
 13.  14.  18.5 29.  15.  22.  19.  24.  23.5 14.  29.5 17. ]

In [24]:
#checking the accuracy of the decisiontree model
accuracy = r2_score(strat_test_set['mpg'],predictions_decisiontree)
print(f"Accuracy (R2 Score) is: {accuracy:.2%}")

Accuracy (R2 Score) is: 77.28%

In [25]:
#randomforest Model
strat_test_set_features = strat_test_set.drop(['mpg'],axis=1)
prepared_test_data = num_pipeline.transform(strat_test_set_features)
predictions_randomforest = randomforest.predict(prepared_test_data)
print(predictions_randomforest)

[20.214 20.925 14.    22.463 26.03  32.635 23.052 35.507 14.665 21.305
 37.357 22.341 21.825 22.835 30.692 20.749 30.376 22.546 28.565 35.151
 12.86  23.325 34.21  14.485 18.338 15.6   35.309 24.505 14.12  15.166
 18.645 31.636 14.25  21.675 19.418 25.835 24.203 13.925 33.603 18.309]

In [26]:
#checking the accuracy of the randomforest model
accuracy = r2_score(strat_test_set['mpg'],predictions_randomforest)
print(f"Accuracy (R2 Score) is: {accuracy:.2%}")

Accuracy (R2 Score) is: 84.45%

In [33]:
#Doing feature engineeing (adding some extra columns to impove results.)
copy_miles_per_gallon['power_to_weight'] = copy_miles_per_gallon['horsepower']/copy_miles_per_gallon['weight']

      mpg  cylinders  displacement  ...  acceleration  model_year  power_to_weight
0    18.0          8         307.0  ...          12.0          70         0.037100
1    15.0          8         350.0  ...          11.5          70         0.044679
2    18.0          8         318.0  ...          11.0          70         0.043655
3    16.0          8         304.0  ...          12.0          70         0.043694
4    17.0          8         302.0  ...          10.5          70         0.040591
..    ...        ...           ...  ...           ...         ...              ...
393  27.0          4         140.0  ...          15.6          82         0.030824
394  44.0          4          97.0  ...          24.6          82         0.024413
395  32.0          4         135.0  ...          11.6          82         0.036601
396  28.0          4         120.0  ...          18.6          82         0.030095
397  31.0          4         119.0  ...          19.4          82         0.030147

[398 rows x 8 columns]

In [37]:
copy_miles_per_gallon['weight_per_cylinders'] = copy_miles_per_gallon['weight']/copy_miles_per_gallon['cylinders']

In [40]:
copy_miles_per_gallon['displacement_per_cylinders'] = copy_miles_per_gallon['displacement']/copy_miles_per_gallon['cylinders']

In [43]:
copy_miles_per_gallon['horsepower_per_cylinders'] = copy_miles_per_gallon['horsepower']/copy_miles_per_gallon['cylinders']

In [45]:
copy_miles_per_gallon['specific_power'] = copy_miles_per_gallon['horsepower']/copy_miles_per_gallon['displacement']

In [47]:
copy_miles_per_gallon['performance_score'] = (copy_miles_per_gallon['horsepower']*copy_miles_per_gallon['acceleration'])/copy_miles_per_gallon['weight']

In [50]:
copy_miles_per_gallon['weight_efficiency'] = 1/copy_miles_per_gallon['weight']

In [52]:
copy_miles_per_gallon['actual_year'] = copy_miles_per_gallon['model_year'] + 1900

In [54]:
copy_miles_per_gallon['car_age'] = 2026 - copy_miles_per_gallon['actual_year']

In [55]:
copy_miles_per_gallon

      mpg  cylinders  displacement  ...  weight_efficiency  actual_year  car_age
0    18.0          8         307.0  ...           0.000285         1970       56
1    15.0          8         350.0  ...           0.000271         1970       56
2    18.0          8         318.0  ...           0.000291         1970       56
3    16.0          8         304.0  ...           0.000291         1970       56
4    17.0          8         302.0  ...           0.000290         1970       56
..    ...        ...           ...  ...                ...          ...      ...
393  27.0          4         140.0  ...           0.000358         1982       44
394  44.0          4          97.0  ...           0.000469         1982       44
395  32.0          4         135.0  ...           0.000436         1982       44
396  28.0          4         120.0  ...           0.000381         1982       44
397  31.0          4         119.0  ...           0.000368         1982       44

[398 rows x 16 columns]

In [57]:
split = StratifiedShuffleSplit(n_splits=1,test_size=0.1,random_state=89)
for train_index,test_index in split.split(copy_miles_per_gallon,copy_miles_per_gallon['cylinders']):
  strat_train_set_more_features = copy_miles_per_gallon.loc[train_index]
  strat_test_set_more_features = copy_miles_per_gallon.loc[test_index]

In [60]:
new_labels = strat_train_set_more_features['mpg']
new_features = strat_train_set_more_features.drop(['mpg'],axis=1)

In [63]:
prepared_new_data = num_pipeline.fit_transform(new_features)

In [64]:
#training the linear model on new dataset
linearmodel.fit(prepared_new_data,new_labels)

LinearRegression()

In [65]:
#now passing the test data in linear model
test_more_features = strat_test_set_more_features.drop(['mpg'],axis=1)
prepared_new_test_data = num_pipeline.transform(test_more_features)
new_predictions_linear = linearmodel.predict(prepared_new_test_data)
print(new_predictions_linear)

[36.6500386  23.62038848 22.66217464 18.03016613 28.5255807  26.00351093
 17.28830333 19.90197375 24.40334477 35.34109809 18.97415039 29.33341847
 30.60547053 24.21733738 24.08239857 14.62558781 21.06833738 31.81450475
 23.24435886 28.61348942 12.34631587 19.12915095 38.84375463 12.74295424
 16.9267632  23.61345095 13.76024277 23.63789304 32.64003742 29.90005698
 14.44386128 33.18794676 28.50041654 35.50878397 14.587717   15.06968211
 27.3257625  10.92046877 21.26158404 30.54360472]

In [66]:
#checking the accuracy of the linear model on new dataset
accuracy = r2_score(strat_test_set_more_features['mpg'],new_predictions_linear)
print(f"Accuracy (R2 Score) is: {accuracy:.2%}")

Accuracy (R2 Score) is: 77.35%

In [67]:
#training the decisiontree on new dataset
decisiontree.fit(prepared_new_data,new_labels)

DecisionTreeRegressor()

In [68]:
#now passing the test data to decisiontree model
test_more_features_2 = strat_test_set_more_features.drop(['mpg'],axis=1)
prepared_new_test_data_2 = num_pipeline.transform(test_more_features_2)
new_predictions_decisiontree = decisiontree.predict(prepared_new_test_data_2)
print(new_predictions_decisiontree)

[37.  23.  24.  22.  25.5 22.3 14.  20.3 27.  35.  18.  28.  25.4 20.8
 17.5 13.  22.4 31.  20.8 24.5 15.  17.5 39.  11.  15.  22.4 18.  26.
 33.  31.5 16.5 37.  28.  32.8 14.  17.  28.  12.  20.5 26. ]

In [69]:
#checking the accuracy of the decisiontree model on new dataset
accuracy = r2_score(strat_test_set_more_features['mpg'],new_predictions_decisiontree)
print(f"Accuracy (R2 Score) is: {accuracy:.2%}")

Accuracy (R2 Score) is: 64.30%

In [70]:
#training the randomforest on new dataset
randomforest.fit(prepared_new_data,new_labels)

RandomForestRegressor()

In [71]:
#now passing the test data to randomforest model
test_more_features_3 = strat_test_set_more_features.drop(['mpg'],axis=1)
prepared_new_test_data_3 = num_pipeline.transform(test_more_features_3)
new_predictions_randomforest = randomforest.predict(prepared_new_test_data_3)
print(new_predictions_randomforest)

[36.073 21.709 22.406 21.256 24.993 25.029 15.863 20.613 26.557 32.115
 19.491 27.588 29.652 21.534 20.736 14.108 20.226 30.524 20.569 25.183
 14.725 18.559 38.319 11.95  16.136 21.054 16.883 23.81  33.913 28.479
 13.463 36.255 28.449 36.534 13.585 16.17  25.325 11.89  19.221 28.902]

In [72]:
#checking the accuracy of the randomforest model on new dataset
accuracy = r2_score(strat_test_set_more_features['mpg'],new_predictions_randomforest)
print(f"Accuracy (R2 Score) is: {accuracy:.2%}")

Accuracy (R2 Score) is: 78.37%

In [73]:
#Best model is Randomforest and use the dataset without feature engineering as increase in new columns causes decrease in the accuracy of the models